# Generated by Django 5.0 on 2023-12-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=255),
        ),
    ]
