# Generated by Django 5.0 on 2023-12-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarage', '0002_alter_user_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
