# Generated by Django 5.0 on 2023-12-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarage', '0003_alter_user_options_alter_user_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
