# Generated by Django 5.0 on 2023-12-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarage', '0004_alter_admin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
