# Generated by Django 5.0 on 2023-12-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarage', '0005_alter_admin_options_alter_admin_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='sart_time',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='garage',
            name='title',
            field=models.CharField(max_length=35, null=True, unique=True),
        ),
    ]
