# Generated by Django 5.0 on 2023-12-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartgarage', '0006_rename_sart_time_reservation_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
